version: "2.12.2"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_cont
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - "mysql_host"

volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
